/**
 * A mutation is a single intent-to-change-state generated by a client.
 *
 * Mutations carry their own client-generated `idempotencyKey` (ULID) so the
 * server can recognize a retry of the same logical operation — even after a
 * network partition, browser refresh, or scanner crash. The key is the
 * cornerstone of "exactly-once" delivery semantics in this library: the
 * client may send the same mutation many times, but the server applies it
 * at most once.
 *
 * `payload` is intentionally opaque (`unknown`). The library doesn't care
 * what shape your domain mutations take — admit-guest, capture-payment,
 * cancel-order — only that they each have a stable key and a fingerprint.
 */
export interface Mutation<P = unknown> {
  /** ULID generated client-side at mutation creation time. Stable across retries. */
  idempotencyKey: string;
  /** Domain-specific mutation type. Lets the server route to the right handler. */
  type: string;
  /** The actual payload of the mutation. */
  payload: P;
  /** Client clock at creation. Used for ordering when the server hasn't assigned a seq yet. */
  clientTs: number;
  /** Optional: which device produced this. Useful for debugging and metrics. */
  clientId?: string;
}

/**
 * The result of a server processing a mutation. Once a mutation is committed,
 * it gets a monotonic `seqId` assigned by the server. Clients use seqIds for
 * catch-up replay: "give me everything since seq 1742."
 */
export interface CommitResult<R = unknown> {
  idempotencyKey: string;
  seqId: number;
  /** True if this idempotencyKey was a duplicate of a prior commit. */
  duplicate: boolean;
  /** The original commit's result is replayed for duplicates. */
  result: R;
  /** Server clock at commit. */
  serverTs: number;
}

/**
 * An event published to the realtime broadcast channel. Either a mutation
 * has been provisionally announced ("pending") or definitively committed
 * ("commit"). Other clients use this to update their UI optimistically and
 * reconcile.
 */
export type SyncEvent<R = unknown> =
  | {
      kind: 'pending';
      idempotencyKey: string;
      type: string;
      clientId?: string;
      announcedAt: number;
    }
  | ({ kind: 'commit' } & CommitResult<R>);
